### ISSUE TITLE
Add MultiPatch support

### ISSUE THREAD

**Issue by tarun-mitruka** [rath3t/dune-iga#17] opened 2023-09-29 09:45 UTC
- [ ] Add support to read in more than one patch
- [ ] Provide algorithms to "glue" patches together, conforming and non-conforming, (also self-glueing edges for the case of a torus should be supported)
- [ ] Decide interface for patch coupling iterators, based on element intersection

**Comment by henrij22** [comment] 2024-04-22 09:26
This is a duplicate of #29

**Closed** 2024-04-22 09:26 UTC
